MVCProject/Models/Aboutu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCProject.Models;

public partial class Aboutu
{
    public decimal AboutId { get; set; }

    public string? Aboutusimgbanner { get; set; }
    [DisplayName("Main Image")]
    public string? Aboutusmainimg { get; set; }
    [DisplayName("About Us Description")]
    public string? Aboutusdescription { get; set; }
    [DisplayName("Trusted info")]
    public string? Trustedinfo { get; set; }
    [DisplayName("Proffissonal info")]
    public string? Profinfo { get; set; }
    [DisplayName("Expert info")]
    public string? Expertinfo { get; set; }
    [NotMapped]
    public IFormFile ImageFile { get; set; }
}

MVCProject/Controllers/AboutusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCProject.Models;

namespace MVCProject.Controllers
{
    public class AboutusController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AboutusController(ModelContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Aboutus
        public async Task<IActionResult> Index()
        {
              return _context.Aboutus != null ? 
                          View(await _context.Aboutus.ToListAsync()) :
                          Problem("Entity set 'ModelContext.Aboutus'  is null.");
        }

        // GET: Aboutus/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null || _context.Aboutus == null)
            {
                return NotFound();
            }

            var aboutu = await _context.Aboutus
                .FirstOrDefaultAsync(m => m.AboutId == id);
            if (aboutu == null)
            {
                return NotFound();
            }

            return View(aboutu);
        }

        // GET: Aboutus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aboutus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AboutId,ImageFile,Aboutusdescription,Trustedinfo,Profinfo,Expertinfo")] Aboutu aboutu)
        {
            if (ModelState.IsValid)
            {
                if (aboutu.ImageFile != null)
                {
                    string wwwrootPath = _webHostEnvironment.WebRootPath;
                    string imageName = Guid.NewGuid().ToString() + "_" + aboutu.ImageFile.FileName;
                    string fullPath = Path.Combine(wwwrootPath + "/Images/", imageName);
                    using (var fileStream = new FileStream(fullPath, FileMode.Create))
                    {
                        aboutu.ImageFile.CopyToAsync(fileStream);
                    }
                    aboutu.Aboutusmainimg = imageName;
                }
                _context.Add(aboutu);
                await _context.SaveChangesAsync();
                TempData["message"] = "you are successfuly created the record";
                return RedirectToAction(nameof(Index));
            }
            return View(aboutu);
        }

        // GET: Aboutus/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null || _context.Aboutus == null)
            {
                return NotFound();
            }

            var aboutu = await _context.Aboutus.FindAsync(id);
            if (aboutu == null)
            {
                return NotFound();
            }
            return View(aboutu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("AboutId,ImageFile,Aboutusdescription,Trustedinfo,Profinfo,Expertinfo")] Aboutu aboutu)
        {
            if (id != aboutu.AboutId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (aboutu.ImageFile != null)
                    {
                        // Check if the file is an image
                        var supportedTypes = new[] { "image/jpeg", "image/png", "image/gif", "image/bmp", "image/webp" };
                        var mimeType = aboutu.ImageFile.ContentType;

                        if (!supportedTypes.Contains(mimeType))
                        {
                            TempData["message"] = "please only upload image file only try again!";
                            return View(aboutu);
                        }

                        string wwwrootPath = _webHostEnvironment.WebRootPath;
                        string imageName = Guid.NewGuid().ToString() + "_" + aboutu.ImageFile.FileName;
                        string fullPath = Path.Combine(wwwrootPath + "/Images/", imageName);

                        using (var fileStream = new FileStream(fullPath, FileMode.Create))
                        {
                            await aboutu.ImageFile.CopyToAsync(fileStream);
                        }
                        aboutu.Aboutusmainimg = imageName;
                    }

                    _context.Update(aboutu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutuExists(aboutu.AboutId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["message"] = "You have successfully updated the record.";
                return RedirectToAction(nameof(Index));
            }
            return View(aboutu);
        }








        // POST: Aboutus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(decimal id, [Bind("AboutId,ImageFile,Aboutusdescription,Trustedinfo,Profinfo,Expertinfo")] Aboutu aboutu)
        //{
        //    if (id != aboutu.AboutId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            if (aboutu.ImageFile != null)
        //            {
        //                string wwwrootPath = _webHostEnvironment.WebRootPath;
        //                string imageName = Guid.NewGuid().ToString() + "_" + aboutu.ImageFile.FileName;
        //                string fullPath = Path.Combine(wwwrootPath + "/Images/", imageName);
        //                using (var fileStream = new FileStream(fullPath, FileMode.Create))
        //                {
        //                    aboutu.ImageFile.CopyToAsync(fileStream);
        //                }
        //                aboutu.Aboutusmainimg = imageName;
        //            }
        //                _context.Update(aboutu);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!AboutuExists(aboutu.AboutId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        TempData["message"] = "you are successfuly updated the record";
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(aboutu);
        //}

        // GET: Aboutus/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null || _context.Aboutus == null)
            {
                return NotFound();
            }

            var aboutu = await _context.Aboutus
                .FirstOrDefaultAsync(m => m.AboutId == id);
            if (aboutu == null)
            {
                return NotFound();
            }

            return View(aboutu);
        }

        // POST: Aboutus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            if (_context.Aboutus == null)
            {
                return Problem("Entity set 'ModelContext.Aboutus'  is null.");
            }
            var aboutu = await _context.Aboutus.FindAsync(id);
            if (aboutu != null)
            {
                _context.Aboutus.Remove(aboutu);
            }
            
            await _context.SaveChangesAsync();
            TempData["message"] = "you are successfuly deleted the record";
            return RedirectToAction(nameof(Index));
        }

        private bool AboutuExists(decimal id)
        {
          return (_context.Aboutus?.Any(e => e.AboutId == id)).GetValueOrDefault();
        }
    }
}

MVCProject/Views/Aboutus/Create.cshtml
@model MVCProject.Models.Aboutu

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="main-panel">
    <div class="content-wrapper">
        <h1>Create</h1>

        <h4>About us Page</h4>
        <hr />
<div class="row">
    <div class="col-md-4">
                <form asp-action="Create" asp-controller="Aboutus" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aboutusdescription" class="control-label"></label>
                <input asp-for="Aboutusdescription" class="form-control" />
                <span asp-validation-for="Aboutusdescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trustedinfo" class="control-label"></label>
                <input asp-for="Trustedinfo" class="form-control" />
                <span asp-validation-for="Trustedinfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profinfo" class="control-label"></label>
                <input asp-for="Profinfo" class="form-control" />
                <span asp-validation-for="Profinfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expertinfo" class="control-label"></label>
                <input asp-for="Expertinfo" class="form-control" />
                <span asp-validation-for="Expertinfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
            <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
</div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCProject/Views/Aboutus/Delete.cshtml
@model MVCProject.Models.Aboutu

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>About us Page</h4>
    <hr />
            <div class="card mb-3">

                <div class="card-body">
                    <h5 class="card-title">
                        @Html.DisplayFor(model => model.ImageFile)
                        <img src=@Url.Content("~/Images/" + Model.Aboutusmainimg)
                             asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                        <br />
                        <p>
                            @Html.DisplayNameFor(model => model.Aboutusdescription) </br>
                            @Html.DisplayFor(model => model.Aboutusdescription)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.Trustedinfo)
                            </br>
                            @Html.DisplayFor(model => model.Trustedinfo)
                        </p>
                    </h5>
                    <p class="card-text">
                        @Html.DisplayNameFor(model => model.Profinfo)
                        <br /> @Html.DisplayFor(model => model.Profinfo)
                    </p>
                    <p class="card-text">
                        @Html.DisplayNameFor(model => model.Expertinfo)
                        <br /> @Html.DisplayFor(model => model.Expertinfo)
                    </p>

                </div>

            </div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AboutId" />
        <input type="submit" value="Delete" class="btn btn-sm btn-danger" /> |
                <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
    </form>
</div>
</div></div>

MVCProject/Views/Aboutus/Details.cshtml
@model MVCProject.Models.Aboutu

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
<h1>Details</h1>

<div>
    <h4>About us Page</h4>
    <hr />
            <div class="card mb-3">

                <div class="card-body">
                    <h5 class="card-title">
                        @Html.DisplayFor(model => model.ImageFile)
                        <img src=@Url.Content("~/Images/" + Model.Aboutusmainimg)
                             asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                        <br />
                        <p>
                           @Html.DisplayNameFor(model => model.Aboutusdescription) </br>
                            @Html.DisplayFor(model => model.Aboutusdescription)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.Trustedinfo)
                             </br>
                            @Html.DisplayFor(model => model.Trustedinfo)
                        </p>
                    </h5>
                    <p class="card-text">
                        @Html.DisplayNameFor(model => model.Profinfo)
                        <br /> @Html.DisplayFor(model => model.Profinfo)
                    </p>
                    <p class="card-text">
                        @Html.DisplayNameFor(model => model.Expertinfo)
                        <br /> @Html.DisplayFor(model => model.Expertinfo)
                    </p>

                </div>

            </div>
   
</div>
<div>
            <a asp-action="Edit" asp-route-id="@Model?.AboutId" class=" btn btn-sm bg-gradient-primary">Edit</a> |
            <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
</div>
</div></div>

MVCProject/Views/Aboutus/Edit.cshtml
@model MVCProject.Models.Aboutu

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">

        toastr["warning"]("you must upload image File Only", "Masterchef")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}
<div class="main-panel">
    <div class="content-wrapper">
        <h1>Edit</h1>

        <h4>About us Page</h4>
        <hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AboutId" />
            
            <div class="form-group">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <input asp-for="ImageFile" class="form-control" />
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aboutusdescription" class="control-label"></label>
                <input asp-for="Aboutusdescription" class="form-control" />
                <span asp-validation-for="Aboutusdescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trustedinfo" class="control-label"></label>
                <input asp-for="Trustedinfo" class="form-control" />
                <span asp-validation-for="Trustedinfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profinfo" class="control-label"></label>
                <input asp-for="Profinfo" class="form-control" />
                <span asp-validation-for="Profinfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expertinfo" class="control-label"></label>
                <input asp-for="Expertinfo" class="form-control" />
                <span asp-validation-for="Expertinfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
            <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
</div>
</div></div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCProject/Views/Aboutus/Index.cshtml
@model IEnumerable<MVCProject.Models.Aboutu>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}
<div class="main-panel">
    <div class="content-wrapper">
<h1 style="font-family:'Times New Roman', Times, serif">Index</h1>

<p>
            @* <a asp-action="Create" class=" btn btn-sm bg-gradient-primary">Create New</a> *@
</p>
<table class="table" id="example">
    <thead>
        <tr>
         
            <th>
                @Html.DisplayNameFor(model => model.Aboutusmainimg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aboutusdescription)
            </th>
          
            <th>
                Control
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                            <img src=@Url.Content("~/Images/" + @item.Aboutusmainimg)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aboutusdescription)
            </td>
          
            <td>
                            <a asp-action="Edit" asp-route-id="@item.AboutId" class=" btn btn-sm bg-gradient-primary">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.AboutId" class=" btn btn-sm bg-gradient-primary">Details</a> |
                           @*  <a asp-action="Delete" asp-route-id="@item.AboutId" class=" btn btn-sm bg-gradient-primary">Delete</a> *@
            </td>
        </tr>
}
    </tbody>
</table>
</div></div>