MVCProject/Models/Homepage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCProject.Models;

public partial class Homepage
{
    public decimal PageId { get; set; }

    public string? Phonenum { get; set; }
    [DisplayName("Image logo")]
    public string? Imglogo { get; set; }
    [NotMapped]
    public IFormFile ImageFile { get; set; }
    [DisplayName(" First Banner")]
    public string? Imgbannerone { get; set; }
    //[NotMapped]
    //public IFormFile ImageFile1 { get; set; }
    [DisplayName(" Second Banner")]
    public string? Imgbannertwo { get; set; }
    //[NotMapped]
    //public IFormFile ImageFile2 { get; set; }
    [DisplayName(" Third Banner")]
    public string? Imgbannerthree { get; set; }
    //[NotMapped]
    //public IFormFile ImageFile3 { get; set; }
    [DisplayName("  Banner Description")]
    public string? Bannerdescription { get; set; }
    [DisplayName(" Image Desgin")]
    public string? Imgonedesign { get; set; }
    //[NotMapped]
    //public IFormFile ImageFile4 { get; set; }
    [DisplayName(" Image Desgin two")]
    public string? Imgtwodesign { get; set; }
    //[NotMapped]
    //public IFormFile ImageFile5 { get; set; }
}

MVCProject/Controllers/HomepagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCProject.Models;

namespace MVCProject.Controllers
{
    public class HomepagesController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public HomepagesController(ModelContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;   
        }

        // GET: Homepages
        public async Task<IActionResult> Index()
        {
              return _context.Homepages != null ? 
                          View(await _context.Homepages.ToListAsync()) :
                          Problem("Entity set 'ModelContext.Homepages'  is null.");
        }

        // GET: Homepages/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null || _context.Homepages == null)
            {
                return NotFound();
            }

            var homepage = await _context.Homepages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (homepage == null)
            {
                return NotFound();
            }

            return View(homepage);
        }

        // GET: Homepages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Homepages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,Phonenum,ImageFile,Bannerdescription")] Homepage homepage)
        {
            if (ModelState.IsValid)
            {
                if (homepage.ImageFile != null)
                {
                    // Check if the file is an image
                    var supportedTypes = new[] { "image/jpeg", "image/png", "image/gif", "image/bmp", "image/webp" };
                    var fileExtension = Path.GetExtension(homepage.ImageFile.FileName).ToLower();
                    var mimeType = homepage.ImageFile.ContentType;

                    if (!supportedTypes.Contains(mimeType))
                    {
                        TempData["message"] = "please Upload only image type try again.";
                        return View(homepage);
                    }

                    string wwwrootPath = _webHostEnvironment.WebRootPath;
                    string imageName = Guid.NewGuid().ToString() + "_" + homepage.ImageFile.FileName;
                    string fullPath = Path.Combine(wwwrootPath + "/img/", imageName);

                    using (var fileStream = new FileStream(fullPath, FileMode.Create))
                    {
                        await homepage.ImageFile.CopyToAsync(fileStream);
                    }
                    homepage.Imglogo = imageName;

                    _context.Add(homepage);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "You have successfully created the record.";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("ImageFile", "Please upload an image file.");
                }
            }
            return View(homepage);
        }



        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("PageId,Phonenum,ImageFile,Bannerdescription")] Homepage homepage)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        if (homepage.ImageFile != null)
        //        {
        //            string wwwrootPath = _webHostEnvironment.WebRootPath;
        //            string imageName = Guid.NewGuid().ToString() + "_" + homepage.ImageFile.FileName;
        //            string fullPath = Path.Combine(wwwrootPath + "/img/", imageName);

        //            using (var fileStream = new FileStream(fullPath, FileMode.Create))
        //            {
        //                await homepage.ImageFile.CopyToAsync(fileStream);
        //            }
        //            homepage.Imglogo = imageName;
        //        }

        //        _context.Add(homepage);
        //        await _context.SaveChangesAsync();
        //        TempData["message"] = "you are successfuly created the record";
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(homepage);
        //}

        // GET: Homepages/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null || _context.Homepages == null)
            {
                return NotFound();
            }

            var homepage = await _context.Homepages.FindAsync(id);
            if (homepage == null)
            {
                return NotFound();
            }
            return View(homepage);
        }

        // POST: Homepages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("PageId,Phonenum,ImageFile,Bannerdescription")] Homepage homepage)
        {
            if (id != homepage.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (homepage.ImageFile != null)
                    {
                        // Check if the file is an image
                        var supportedTypes = new[] { "image/jpeg", "image/png", "image/gif", "image/bmp", "image/webp" };
                        var mimeType = homepage.ImageFile.ContentType;

                        if (!supportedTypes.Contains(mimeType))
                        {
                            TempData["message"] = "please Upload only image type try again.";
                            return View(homepage);
                        }

                        string wwwrootPath = _webHostEnvironment.WebRootPath;
                        string imageName = Guid.NewGuid().ToString() + "_" + homepage.ImageFile.FileName;
                        string fullPath = Path.Combine(wwwrootPath + "/img/", imageName);
                        using (var fileStream = new FileStream(fullPath, FileMode.Create))
                        {
                            await homepage.ImageFile.CopyToAsync(fileStream);
                        }
                        homepage.Imglogo = imageName;
                    }

                    _context.Update(homepage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HomepageExists(homepage.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["message"] = "You have successfully updated the record.";
                return RedirectToAction(nameof(Index));
            }
            return View(homepage);
        }
        //public async Task<IActionResult> Edit(decimal id, [Bind("PageId,Phonenum,ImageFile,Bannerdescription")] Homepage homepage)
        //{
        //    if (id != homepage.PageId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            if (homepage.ImageFile != null)
        //            {
        //                string wwwrootPath = _webHostEnvironment.WebRootPath;
        //                string imageName = Guid.NewGuid().ToString() + "_" + homepage.ImageFile.FileName;
        //                string fullPath = Path.Combine(wwwrootPath + "/img/", imageName);
        //                using (var fileStream = new FileStream(fullPath, FileMode.Create))
        //                {
        //                    homepage.ImageFile.CopyToAsync(fileStream);
        //                }
        //                homepage.Imglogo = imageName;
        //            }
        //            //if (homepage.ImageFile1 != null)
        //            //{
        //            //    string wwwrootPath = _webHostEnvironment.WebRootPath;
        //            //    string imageName = Guid.NewGuid().ToString() + "_" + homepage.ImageFile1.FileName;
        //            //    string fullPath = Path.Combine(wwwrootPath + "/img/", imageName);
        //            //    using (var fileStream = new FileStream(fullPath, FileMode.Create))
        //            //    {
        //            //        homepage.ImageFile1.CopyToAsync(fileStream);
        //            //    }
        //            //    homepage.Imgbannerone = imageName;
        //            //}
        //            //if (homepage.ImageFile2 != null)
        //            //{
        //            //    string wwwrootPath = _webHostEnvironment.WebRootPath;
        //            //    string imageName = Guid.NewGuid().ToString() + "_" + homepage.ImageFile2.FileName;
        //            //    string fullPath = Path.Combine(wwwrootPath + "/img/", imageName);
        //            //    using (var fileStream = new FileStream(fullPath, FileMode.Create))
        //            //    {
        //            //        homepage.ImageFile2.CopyToAsync(fileStream);
        //            //    }

MVCProject/Views/Homepages/Create.cshtml
@model MVCProject.Models.Homepage

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">

        toastr["warning"]("you must upload image File Only", "Masterchef")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}
<div class="main-panel">
    <div class="content-wrapper">
<h1>Create</h1>

<h4>Homepage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
                <form asp-action="Create" asp-controller="Homepages" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Phonenum" class="control-label"></label>
                <input asp-for="Phonenum" class="form-control" />
                <span asp-validation-for="Phonenum" class="text-danger"></span>
            </div>
            <div class="form-group">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <input asp-for="ImageFile" class="form-control" />
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
           @*  <div class="form-group">
                        <label asp-for="ImageFile1" class="control-label"></label>
                        <input asp-for="ImageFile1" class="form-control" />
                        <span asp-validation-for="ImageFile1" class="text-danger"></span>
            </div>
            <div class="form-group">
                        <label asp-for="ImageFile2" class="control-label"></label>
                        <input asp-for="ImageFile2" class="form-control" />
                <span asp-validation-for="ImageFile2" class="text-danger"></span>
            </div>
            <div class="form-group">
                        <label asp-for="ImageFile3" class="control-label"></label>
                <input asp-for="ImageFile3" class="form-control" />
                <span asp-validation-for="ImageFile3" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Bannerdescription" class="control-label"></label>
                <input asp-for="Bannerdescription" class="form-control" />
                <span asp-validation-for="Bannerdescription" class="text-danger"></span>
            </div>
           @*  <div class="form-group">
                        <label asp-for="ImageFile4" class="control-label"></label>
                        <input asp-for="ImageFile4" class="form-control" />
                        <span asp-validation-for="ImageFile4" class="text-danger"></span>
            </div>
            <div class="form-group">
                        <label asp-for="ImageFile5" class="control-label"></label>
                        <input asp-for="ImageFile5" class="form-control" />
                        <span asp-validation-for="ImageFile5" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
            <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
</div>
</div></div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCProject/Views/Homepages/Delete.cshtml
@model MVCProject.Models.Homepage

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <h1>Delete</h1>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Home Page</h4>
            <hr />
            <div class="card mb-3">

                <div class="card-body">
                    <h5 class="card-title"> Delete </h5>
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Phonenum)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Phonenum)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Imglogo)
                            </dt>
                            <dd class="col-sm-10">
                                <img src=@Url.Content("~/img/" + Model.Imglogo)
                                     asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                            </dd>
                          @*   <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Imgbannerone)
                            </dt>
                            <dd class="col-sm-10">
                                <img src=@Url.Content("~/img/" + Model.Imgbannerone)
                                     asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Imgbannertwo)
                            </dt>
                            <dd class="col-sm-10">
                                <img src=@Url.Content("~/img/" + Model.Imgbannertwo)
                                     asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Imgbannerthree)
                            </dt>
                            <dd class="col-sm-10">
                                <img src=@Url.Content("~/img/" + Model.Imgbannerthree)
                                     asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                            </dd> *@
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Bannerdescription)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Bannerdescription)
                            </dd>
                           @*  <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Imgonedesign)
                            </dt>
                            <dd class="col-sm-10">
                                <img src=@Url.Content("~/img/" + Model.Imgonedesign)
                                     asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Imgtwodesign)
                            </dt>
                            <dd class="col-sm-10">
                                <img src=@Url.Content("~/img/" + Model.Imgtwodesign)
                                     asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                            </dd> *@
                        </dl>

                </div>

            </div>
            <form asp-action="Delete">
                <input type="hidden" asp-for="PageId" />
                <input type="submit" value="Delete" class="btn btn-sm btn-danger" /> |
                <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
            </form>
        </div>
    </div>
</div>

MVCProject/Views/Homepages/Details.cshtml
@model MVCProject.Models.Homepage

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <h1>Details</h1>

        <div>
            <h4>Home Page</h4>
            <hr />
            <div class="card mb-3">

                <div class="card-body">
                    <h5 class="card-title"> Details of Home page </h5>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imglogo)
        </dt>
        <dd class = "col-sm-10">
                            <img src=@Url.Content("~/img/" + Model.Imglogo)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
        </dd>
    @*     <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgbannerone)
        </dt>
        <dd class = "col-sm-10">
                            <img src=@Url.Content("~/img/" + Model.Imgbannerone)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgbannertwo)
        </dt>
        <dd class = "col-sm-10">
                            <img src=@Url.Content("~/img/" + Model.Imgbannertwo)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgbannerthree)
        </dt>
        <dd class = "col-sm-10">
                            <img src=@Url.Content("~/img/" + Model.Imgbannerthree)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
                        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bannerdescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bannerdescription)
        </dd>
       @*  <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgonedesign)
        </dt>
        <dd class = "col-sm-10">
                            <img src=@Url.Content("~/img/" + Model.Imgonedesign)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgtwodesign)
        </dt>
        <dd class = "col-sm-10">
                            <img src=@Url.Content("~/img/" + Model.Imgtwodesign)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
        </dd> *@
    </dl>
</div>
<div>

                    <a asp-action="Edit" asp-route-id="@Model?.PageId" class=" btn btn-sm bg-gradient-primary">Edit</a> |
                    <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
</div>
            </div>
        </div>

        </div></div>

MVCProject/Views/Homepages/Edit.cshtml
@model MVCProject.Models.Homepage

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">

        toastr["warning"]("you must upload image File Only", "Masterchef")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}
<div class="main-panel">
    <div class="content-wrapper">
        <h1>Edit</h1>

        <h4>Homepage</h4>
        <hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Homepages" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PageId" />
            <div class="form-group">
                <label asp-for="Phonenum" class="control-label"></label>
                <input asp-for="Phonenum" class="form-control" />
                <span asp-validation-for="Phonenum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
                    <div class="form-group">
                        <label asp-for="Bannerdescription" class="control-label"></label>
                        <input asp-for="Bannerdescription" class="form-control" />
                        <span asp-validation-for="Bannerdescription" class="text-danger"></span>
                    </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
            <a asp-action="Index" class=" btn btn-sm bg-gradient-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
    </div>
</div>

MVCProject/Views/Homepages/Index.cshtml
@model IEnumerable<MVCProject.Models.Homepage>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (TempData["message"] != null)
{
    <script src="/lib/jquery//dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}
<div class="main-panel">
    <div class="content-wrapper">
<h1 style="font-family:'Times New Roman'">Home Pages</h1>

<p>
         @*  <a asp-action="Create" class="  btn btn-sm hvr-hover bg-gradient-primary">Create New</a>  *@
</p>
<table class="table" id="example">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Phonenum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imglogo)
            </th>
           @*  <th>
                @Html.DisplayNameFor(model => model.Imgbannerone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imgbannertwo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imgbannerthree)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Bannerdescription)
            </th>
          @*   <th>
                @Html.DisplayNameFor(model => model.Imgonedesign)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imgtwodesign)
            </th> *@
            <th> Control</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Phonenum)
            </td>
            <td>
                            <img src=@Url.Content("~/img/" + @item.Imglogo)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td>
         @*    <td>
                             <img src=@Url.Content("~/Images/" + @item.Imgbannerone)
                                                                                  asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td>
            <td>
                
                            <img src=@Url.Content("~/img/" + @item.Imgbannertwo)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td>
            <td>
                
                            <img src=@Url.Content("~/img/" + @item.Imgbannerthree)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Bannerdescription)
            </td>
           @*  <td>
              
                            <img src=@Url.Content("~/img/" + @item.Imgonedesign)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td>
            <td>
               
                            <img src=@Url.Content("~/img/" + @item.Imgtwodesign)
                                 asp-append-version="true" style="border-radius:20%;" width="300px" height="200px" />
            </td> *@
            <td>
                            <a asp-action="Edit" asp-route-id="@item.PageId" class="btn btn-sm hvr-hover bg-gradient-primary">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.PageId" class="btn btn-sm hvr-hover bg-gradient-primary">Details</a> 
                            <a asp-action="Delete" asp-route-id="@item.PageId" class="btn btn-sm hvr-hover bg-gradient-primary">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
        <div />
            <div />